### PR TITLE
Update Codesniffer and fix all the things

### PR DESCRIPTION
**Pull request by mondrake**
This PR

- allows Composer to pick a more recent version of codesniffer
- introduces a `phpcs.xml` file to guide the code sniffing
- enforces the short array syntax introduced in #120 
- allows multiple classes per php file (which is against PSR2 std, a todo to fix in the future)
- puts all tests under a namespace `Pel\Test` (they were not!)
- corrects all the newly identified code style errors
- adds code sniffing to the TEST code also (it was not)

### CODE REVIEW

**Comment by weberhofer** [comment]
I like the changes but have two questions:
- What's the reason for renaming the directory?
- I'd not like to have more than one class in a file. Why should we have that?

**Comment by mondrake** [comment]
Re 1 - the PHP lexer fails if there is a dash in the namespace - it probably tries to interpret it as a 'minus' and evaluate an expression

Re 2 - I agree it is better not :) but that is the current status in 2 test files, and I would suggest to address that in another issue - this one is big enough by itself

**Comment by mondrake** [comment]
Uhm... in `master` the number of tests executed in 64, with this PR only 58... something got lost. Will check.

@weberhofer thinking again about point 1 above - we may move **only** the .php files from `test\image-tests` to a new 'test\Camera' folder, so that the the namespace of the test classes will become `Pel\Test\Camera`, and leave the actual image files where they are.

**Comment by weberhofer** [comment]
Ok. This is a good reason for renaming. Thank you for continuing cleaning up the code!

**Pull request merged**
