### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by mondrake**

### CODE REVIEW

**Comment by weberhofer** [comment]
Hi @mondrake! I have just submitted a patch dropping support for PHP versions before 7.1. This allows using more modern constructs in the future. I'm looking forward for your updates on PHP 8 compatibility. Thank you for your contributions!

**Comment by mondrake** [comment]
Hi @weberhofer, are you OK to use Symfony PHPUnit-bridge instead of pure PHPUnit, and drop usage og php-coveralls/php-coveralls? I cannot understand what's used for right now, since Scrutinizer already computes code coverage on its own.

**Comment by mondrake** [comment]
@weberhofer I was wrong with php-coveralls/php-coveralls, Scrutinizer requires it in composer.json. This is good to go for me once good old TravisCI catches up and returns a green.

**Comment by weberhofer** [comment]
Thanks, @mondrake!

**Pull request merged**
