### PR TITLE
PHP 7.4 Validate number issue fix

### PR DESCRIPTION
**Pull request by mondrake**
So there's another PHP 7.4 compatibility issue, which happens if a scalar value is passed to PelEntryNumber::validateNumber and is tried to be accessed as an array - PHP 7.4 is much more strict in this case.

Note - this is coming from work being done to make the Drupal [File Metadata Manager](https://www.drupal.org/project/file_mdm) module compatible with PHP 7.4.

Thanks

### CODE REVIEW

**Comment by weberhofer** [comment]
Thanks, @mondrake for investing so much time in updating PEL!

**Comment by mondrake** [comment]
Thanks @weberhofer 

We'll need another release here at some point - I will open an issue for that when I will be done on the downstream fixes.

Thanks!

**Comment by weberhofer** [comment]
Yes, please do so. I'll create the release when you are ready.

**Comment by mondrake** [comment]
@weberhofer just checking - Packagist is not automaticlly updated on commits?

**Comment by weberhofer** [comment]
I don't think so. I'm neither administrator for this project on github nor for the one at packagist. Maybe @lsolesen or @mgeisler can help.

**Pull request merged**
