### PR TITLE
Handle non-numeric values from PelFormat::getSize

### PR DESCRIPTION
**Pull request by hussainweb**
PelFormat::getSize can also return non-numeric values (string, in case of an error). We should handle those cases correctly.

In my case, this is the warning I see (only the relevant backtrace is shown here).
```
Warning: A non-numeric value encountered in lsolesen\pel\PelIfd->loadSingleValue() (line 447 of /var/www/.../vendor/lsolesen/pel/src/PelIfd.php) #0 /var/www/.../web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'A non-numeric v...', '/var/www/...', 447, Array)
#1 /var/www/.../vendor/lsolesen/pel/src/PelIfd.php(447): _drupal_error_handler(2, 'A non-numeric v...', '/var/www/...', 447, Array)
#2 /var/www/.../vendor/lsolesen/pel/src/PelCanonMakerNotes.php(215): lsolesen\pel\PelIfd->loadSingleValue(Object(lsolesen\pel\PelDataWindow), 4908, 71, 19200)
#3 /var/www/.../vendor/lsolesen/pel/src/PelIfd.php(406): lsolesen\pel\PelCanonMakerNotes->load()
#4 /var/www/.../vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 10)
#5 /var/www/.../vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load(Object(lsolesen\pel\PelDataWindow))
#6 /var/www/.../vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load(Object(lsolesen\pel\PelDataWindow))
#7 /var/www/.../vendor/lsolesen/pel/src/PelJpeg.php(286): lsolesen\pel\PelJpeg->load(Object(lsolesen\pel\PelDataWindow))
#8 /var/www/.../vendor/lsolesen/pel/src/PelJpeg.php(123): lsolesen\pel\PelJpeg->loadFile('public://photos...')
```

### CODE REVIEW

**Comment by mondrake** [comment]
@weberhofer it would be good to get this merged and maybe a new release issued since this is giving problems in the Drupal ecosystem: https://www.drupal.org/project/file_mdm/issues/3147118

**Comment by Berdir** [comment]
The problem with this fix is that it will then go into the to the next part, throw an exception there and silently return.

I did a slightly different fix when testing locally, which tests the format size first and if that is not a number, I just return at that point, as whatever follows isn't going to work I think. At least not in my test image.

**Comment by hussainweb** [comment]
@Berdir, can you specify what you mean next part? It's been a while since I wrote this PR so I don't remember the trace I did for the execution.

**Comment by Berdir** [comment]
If you don't go into that if then goes into the else, and then calls             $entry = $this->newEntryFromData($tag, $format, $components, $data);, which fails with an exception but if you don't have strict or debug mode enabled, it just silently ignores that.

**Comment by weberhofer** [comment]
Thanks, @hussainweb for your contribution. I decided to merge #163 which fixes the same issue.

**Comment by hussainweb** [comment]
Thanks @weberhofer. I didn't have time to update this fix, so I'm happy this got fixed anyway. 🙂

**Pull request closed without merging**
