### PR TITLE
Rating percent tag

### PR DESCRIPTION
**Pull request by artemShelest**
Added new EXIF tags: RatingPercent, OffsetTime, OffsetTimeOriginal and OffsetTimeDigitized.

### CODE REVIEW

**Comment by weberhofer** [comment]
Looks good. What's the difference to #101 which currently fails?

**Comment by artemShelest** [comment]
Hi,
Looks like I made an error while preparing branches, only PelJpeg.php
belongs to #101.
Fixing.

2017-11-03 21:17 GMT+02:00 Johannes Weberhofer <notifications@github.com>:

**Comment by weberhofer** [comment]
Do you have test-cases for the supported tag? A tiny image with a proper license?

**Comment by artemShelest** [comment]
Yes, will update.

**Comment by weberhofer** [comment]
Thanks!

**Pull request merged**
