### PR TITLE
Gracefully handle offset not within boundaries error.

### PR DESCRIPTION
**Pull request by ivangrozni**
Addresses issue: https://github.com/pel/pel/issues/141

### CODE REVIEW

**Comment by fago** [comment]
This sucessfully resolvedd the issue. Not sure about scrutinizer error, but it does not seem related?

**Comment by weberhofer** [comment]
scrutinizer didn't finish correctly. I have re-triggered the tests and it's ok now.

**Comment by weberhofer** [comment]
@ivangrozni , @fago do you have an test-image and an more explicit description to the problem? I have been checking it but i can unfortunately not reproduce the original issue.

**Comment by weberhofer** [comment]
What I really like to have is a test cases that fails on the current code-base and that is fixed with the PR.

**Comment by weberhofer** [comment]
Thanks, @ivangrozni . I could reproduce the issue using your linked images. I could not reproduce any issue with the image uploaded in #141.

I could also write a test-case that shows that for the change fixes the issue on those pictures - will submit it soon. Thank you for your cooperation!

**Pull request merged**
