### PR TITLE
Convert to new array syntax (PHP 5.4)

### PR DESCRIPTION
**Pull request by mondrake**
Since PHP 5.4, the array syntax changed from `array()` to `[]`.

This PR is changing the old syntax to the new syntax. Used the script @ https://github.com/thomasbachem/php-short-array-syntax-converter.

### CODE REVIEW

**Comment by weberhofer** [comment]
Great!

**Comment by weberhofer** [comment]
@bonjarno, I'm sorry, but we are no longer supporting PHP 5.3 as it's really out of date. You could try one of the older versions, but I don't know which was the last one supporting PHP 5.3.

**Comment by bonjarno** [comment]
ok thanks. i am aware of the issue with old 5.3 but am stuck unless I want to move to another business arrangement. long story. I will look more closely at that though because this may need to last more than a year. How do I fetch an older codebase? I will look into it but if you have a quick way for me to get that it would be helpful. Thanks!

**Comment by bonjarno** [comment]
i am setting up a service endpoint on a new host. They have PHP 5.6 or 7. I don't usually go for absolute latest for things like this but will 5.6 work for PEL? Advice, thoughts, opinions? Thx!

**Comment by weberhofer** [comment]
PHP 5.6 is ok. Next time please open an issue and don't use commits or other issues for questions!

**Pull request merged**
