### PR TITLE
Fixes for [pel-Bugs-2979466 ] endless loop in PelIfd->load

### PR DESCRIPTION
**Pull request by mondrake**
A long time standing bug https://sourceforge.net/p/pel/mailman/message/26706741/

This case seems due to wrong data setup in the test image: the INTEROPERABILITY IFD has inside it a pointer to another INTEROPERABILITY IFD. But this is incorrect - we expect only one INTEROPERABILITY IFD in an image file. This leads to an infinite loop.

This PR addresses this by passing the parent IFD type to the load method, so that it can check it's not duplicating IFDs of the same type.

### CODE REVIEW

**Comment by weberhofer** [comment]
@mondrake, I have merged another PR today. It seems this has broken your code.
This PR would fix #11

**Comment by mondrake** [comment]
Yep, very strange, I can't see how they're related. Will check.

**Comment by v1r0x** [comment]
I can't see the problem either. But you call `load()` on IFD in this line without `$type` https://github.com/mondrake/pel/blob/patch-2/src/PelIfd.php#L342
Maybe this leads to some weird behaviour. I try to help investigate the problem tomorrow if I have some free time.

Am I right that just the GH77 test fails?

**Comment by v1r0x** [comment]
Other reason: the test didn't run on older PRs, but now it is fixed and it crashes at another place (maker notes)

**Comment by mondrake** [comment]
I passed the `bug2979466.jpg` image through the `dump-image.php -d` utility.

If I understand correctly, the issue is not what I reported above, but rather that the offset pointer to the INTEROPERABILITY IFD coincides with the offset of the parent EXIF IFD. So that's why it loops endlessly - load EXIF, try to load INTEROPERABILITY but then actually load EXIF again and so forth till end of memory (see excerpt below). So the fix seems wrong - but still cannot understand why the image from another test is failing.

`$ php examples/dump-image.php -d test/images/bug2979466.jpg
Parsing 4304 bytes...
Found APP0 section of length 14
Found APP1 section of length 2722
Parsing 2722 bytes of Exif data...
Parsing 2716 bytes of TIFF data...
Found Intel byte order
First IFD at offset 2502.
Constructing IFD at offset 2502 from 2716 bytes...
Loading 10 entries...
Loading entry with tag 0x010E: ImageDescription (1 of 10)...
Loading entry with tag 0x010F: Make (2 of 10)...
Loading entry with tag 0x0110: Model (3 of 10)...
Loading entry with tag 0x0112: Orientation (4 of 10)...
Loading entry with tag 0x011A: XResolution (5 of 10)...
Loading entry with tag 0x011B: YResolution (6 of 10)...
Loading entry with tag 0x0128: ResolutionUnit (7 of 10)...
Loading entry with tag 0x0132: DateTime (8 of 10)...
Warning: Wrong number of components found for DateTime tag: 21. Expected 20. (PelIfd.php:544)
Loading entry with tag 0x0213: YCbCrPositioning (9 of 10)...
**Loading entry with tag 0x8769: ExifIFDPointer (10 of 10)...
Found sub IFD at offset 8
Constructing IFD at offset 8 from 2716 bytes...**
Loading 30 entries...
Loading entry with tag 0x829A: ExposureTime (1 of 30)...
Loading entry with tag 0x829D: FNumber (2 of 30)...
Loading entry with tag 0x8822: ExposureProgram (3 of 30)...
Loading entry with tag 0x8827: ISOSpeedRatings (4 of 30)...
Loading entry with tag 0x9000: ExifVersion (5 of 30)...
Loading entry with tag 0x9003: DateTimeOriginal (6 of 30)...
Warning: Wrong number of components found for DateTimeOriginal tag: 21. Expected 20. (PelIfd.php:544)
Loading entry with tag 0x9004: DateTimeDigitized (7 of 30)...
Warning: Wrong number of components found for DateTimeDigitized tag: 21. Expected 20. (PelIfd.php:544)
Loading entry with tag 0x9101: ComponentsConfiguration (8 of 30)...
Loading entry with tag 0x9102: CompressedBitsPerPixel (9 of 30)...
Loading entry with tag 0x9204: ExposureBiasValue (10 of 30)...
Loading entry with tag 0x9205: MaxApertureValue (11 of 30)...
Loading entry with tag 0x9207: MeteringMode (12 of 30)...
Loading entry with tag 0x9208: LightSource (13 of 30)...
Loading entry with tag 0x9209: Flash (14 of 30)...
Loading entry with tag 0x920A: FocalLength (15 of 30)...
Loading entry with tag 0x927C: MakerNote (16 of 30)...
Found sub IFD at offset 396
Loading entry with tag 0xA000: FlashPixVersion (17 of 30)...
Loading entry with tag 0xA001: ColorSpace (18 of 30)...
Loading entry with tag 0xA002: PixelXDimension (19 of 30)...
Loading entry with tag 0xA003: PixelYDimension (20 of 30)...
Loading entry with tag 0xA005: InteroperabilityIFDPointer (21 of 30)...
**Found sub IFD at offset 8
Constructing IFD at offset 8 from 2716 bytes...
Loading 30 entries...**
Loading entry with tag 0x829A: ExposureTime (1 of 30)...
Warning: IFD Interoperability cannot hold
  Tag: 0x829A (ExposureTime)
    Format    : 10 (SRational)
    Components: 1
    Value     : Array
(
    [0] => 10
    [1] => 5000
)

    Text      : 10/5000
 (PelIfd.php:1158)
`

**Comment by mondrake** [comment]
@v1r0x most probably the problem is with using a `static` array in https://github.com/pel/pel/blob/master/src/PelIfd.php#L160

The values stored there live with the class across different tests - the data from one image leaks in another instance. 

I have a temp fix to get this going, but I'd say that static needs somehow to be refactored into sth different - maybe some storage at the PelTiff or PelExif level to be passed on to PelIdf objects?

**Comment by weberhofer** [comment]
Good catch, @mondrake! 
@v1r0x, I just had a quick look at $mkNoteValues. Do you really need this array to be static? Please add some phpdoc comments to the introduced variables.

**Comment by mondrake** [comment]
@weberhofer @v1r0x I suggest to do that in another PR

**Comment by v1r0x** [comment]
@mondrake Nice! Good debugging 👍 

@weberhofer I need a variable which is present in all IFDs, because I need the manufacturer (`PelTag::MAKE`) to decide which maker notes parser should be used. Thus, I store information about the maker notes tag (offset, size, ...) and parse it after IFD0 is parsed. A static array looked like a good solution to me. Didn't think of the side effects.
But I think it should be enough to have it in IFD0, so setting it at https://github.com/pel/pel/blob/master/src/PelIfd.php#L294 as local variable and check if it is set at https://github.com/pel/pel/blob/master/src/PelIfd.php#L342 should be enough.
As @mondrake suggested I'd fix that in another PR.

**Comment by weberhofer** [comment]
@mondrake and @v1r0x, many thanks for improving PEL!
@v1r0x I'm looking forward for the above mentioned improvement in your code. Please remove the "PelIfd::$mkNoteValues = array();" from src/PelIfd.php (line 346) at the same time. It should work without.

**Pull request merged**
