### PR TITLE
Support PHP 8.1, drop Travis CI config and add GitHub Actions instead

### PR DESCRIPTION
**Pull request by mondrake**
TravisCI no longer works.

### CODE REVIEW

**Comment by mondrake** [comment]
Adjusted PelIfd to be compatible with PHP 8.1. @weberhofer it would be good to have a release with PHP 8.1 support.

**Comment by umgfoin** [comment]
Looks like this PR would fix problems reported in [nextcloud/maps ssue #652](https://github.com/nextcloud/maps/issues/652).

**Comment by xarinatan** [comment]
is there anything required to get that travis CI pipeline to complete? it's been sad not being able to use the Maps plugin in Nextcloud because of having some photos uploaded in there.. if there's anything I can do to try help let me know.

**Comment by weberhofer** [comment]
Thanks @mondrake  for this pull request. Unfortunately I didn't have any time in the last year to work on pel. Trying to make it better this year!

**Comment by mondrake** [comment]
Thanks @weberhofer !

Any chance you can issue a release for 8.1 support?

**Comment by weberhofer** [comment]
@mondrake I have just released this version.

**Pull request merged**
